import type { Exercise } from "./types";

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: "bench-press",
    name: "Barbell Bench Press",
    category: "push",
    equipment: "barbell",
    isCompound: true,
    incrementKg: 2.5,
    startingWeightKg: 20,
    startingReps: 8,
    sets: 3,
  },
  {
    id: "overhead-press",
    name: "Overhead Press",
    category: "push",
    equipment: "barbell",
    isCompound: true,
    incrementKg: 2.5,
    startingWeightKg: 20,
    startingReps: 6,
    sets: 3,
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    category: "push",
    equipment: "dumbbell",
    isCompound: false,
    incrementKg: 2,
    startingWeightKg: 10,
    startingReps: 8,
    sets: 3,
  },
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    category: "push",
    equipment: "machine",
    isCompound: false,
    incrementKg: 2.5,
    startingWeightKg: 10,
    startingReps: 10,
    sets: 3,
  },
  {
    id: "deadlift",
    name: "Deadlift",
    category: "pull",
    equipment: "barbell",
    isCompound: true,
    incrementKg: 5,
    startingWeightKg: 40,
    startingReps: 5,
    sets: 3,
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    category: "pull",
    equipment: "barbell",
    isCompound: true,
    incrementKg: 2.5,
    startingWeightKg: 30,
    startingReps: 8,
    sets: 3,
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    category: "pull",
    equipment: "bodyweight",
    isCompound: true,
    incrementKg: 0,
    startingWeightKg: 0,
    startingReps: 5,
    sets: 3,
  },
  {
    id: "bicep-curl",
    name: "Bicep Curl",
    category: "pull",
    equipment: "dumbbell",
    isCompound: false,
    incrementKg: 1,
    startingWeightKg: 8,
    startingReps: 10,
    sets: 3,
  },
  {
    id: "back-squat",
    name: "Back Squat",
    category: "legs",
    equipment: "barbell",
    isCompound: true,
    incrementKg: 2.5,
    startingWeightKg: 30,
    startingReps: 5,
    sets: 3,
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "legs",
    equipment: "barbell",
    isCompound: true,
    incrementKg: 2.5,
    startingWeightKg: 30,
    startingReps: 8,
    sets: 3,
  },
  {
    id: "leg-press",
    name: "Leg Press",
    category: "legs",
    equipment: "machine",
    isCompound: true,
    incrementKg: 5,
    startingWeightKg: 40,
    startingReps: 10,
    sets: 3,
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    category: "legs",
    equipment: "machine",
    isCompound: false,
    incrementKg: 2.5,
    startingWeightKg: 20,
    startingReps: 12,
    sets: 3,
  },
];
